-d D:\Software\Gowin\Gowin_project\FFT_tst\impl\gwsynthesis\led_flash.vg
-p GW5A-25A-UBGA324-1
-pn GW5A-LV25UG324ES
-cst D:\Software\Gowin\Gowin_project\FFT_tst\src\led_flash.cst
-cfg D:\Software\Gowin\Gowin_project\FFT_tst\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
